// This file is @generated by prost-build.
/// One fixed-size protected application envelope.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct FixedEnvelope {
    #[prost(bytes = "vec", tag = "1")]
    pub envelope: ::prost::alloc::vec::Vec<u8>,
    /// The key epoch this envelope was sealed under. Cleartext on purpose: it is
    /// per-generation and identical for every client, so it reveals nothing, and
    /// sealing it inside would make a retired key indistinguishable from any
    /// other refusal — leaving a wallet no way to learn it must re-bootstrap.
    #[prost(uint64, tag = "2")]
    pub key_epoch: u64,
}
/// Empty: bootstrap takes no client input. A field here would be an input to
/// authenticate before the client holds any key material, which is exactly the
/// surface this design avoids.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct BootstrapRequest {}
/// Everything a wallet needs to seal a query, and nothing else.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct BootstrapResponse {
    /// Identifies the key generation these keys belong to. Sent back in cleartext
    /// on every QueryPage so a retired key is actionable rather than opaque.
    #[prost(uint64, tag = "1")]
    pub key_epoch: u64,
    /// Seals request envelopes.
    #[prost(bytes = "vec", tag = "2")]
    pub request_key: ::prost::alloc::vec::Vec<u8>,
    /// Opens response envelopes.
    #[prost(bytes = "vec", tag = "3")]
    pub response_key: ::prost::alloc::vec::Vec<u8>,
    /// Human-readable name of the compiled privacy profile, for logs and support.
    ///
    /// Diagnostic, NOT authoritative: do not pin on it. The authoritative profile
    /// identifier is a digest over every logical budget dimension and is already
    /// bound into protected request state, so a query sealed against the wrong
    /// profile fails to open regardless of what this string says. It is named
    /// `profile_label` rather than `profile_id` precisely so it cannot be mistaken
    /// for that identifier.
    #[prost(string, tag = "4")]
    pub profile_label: ::prost::alloc::string::String,
    /// Exact envelope size class, so a wallet pads correctly without guessing.
    #[prost(uint32, tag = "5")]
    pub envelope_bytes: u32,
    /// Legacy reserved field, always empty. Fresh raw evidence is obtained from
    /// GetEvidence before bootstrap; an empty field is never attestation success.
    #[prost(bytes = "vec", tag = "6")]
    pub attestation: ::prost::alloc::vec::Vec<u8>,
    /// Authoritative identifier of the compiled privacy profile: a digest over
    /// every logical budget dimension the runtime compiles in.
    ///
    /// A wallet needs it to build the envelope protection context it seals a
    /// request under. The same bytes are bound into protected request state on
    /// the server side, so a request sealed under a different profile identifier
    /// does not open — which is also why publishing it costs nothing: the digest
    /// covers only compiled, deployment-wide parameters, carries no key material,
    /// and is identical for every client this runtime serves.
    ///
    /// Unlike `profile_label`, this field IS authoritative. Pin on it.
    #[prost(bytes = "vec", tag = "7")]
    pub profile_id: ::prost::alloc::vec::Vec<u8>,
}
/// The verifier contributes only a fresh, exactly 64-byte challenge.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct EvidenceRequest {
    #[prost(bytes = "vec", tag = "1")]
    pub challenge: ::prost::alloc::vec::Vec<u8>,
}
/// Unverified raw evidence. The client must validate the quote and its policy,
/// recompute REPORT_DATA, and match the actual TLS peer's SPKI before bootstrap.
/// These public claims are not trusted merely because the server returned them.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct EvidenceResponse {
    #[prost(uint32, tag = "1")]
    pub transcript_version: u32,
    #[prost(bytes = "vec", tag = "2")]
    pub challenge: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "3")]
    pub tls_spki_sha256: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "4")]
    pub binary_sha256: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "5")]
    pub effective_config_sha256: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "6")]
    pub profile_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint32, tag = "7")]
    pub schema_version: u32,
    #[prost(uint64, tag = "8")]
    pub key_epoch: u64,
    #[prost(uint32, tag = "9")]
    pub checkpoint_height: u32,
    /// Internal canonical block-hash bytes, not reversed display-order hex.
    /// This identifies the public chain checkpoint, not an authenticated ORAM root.
    #[prost(bytes = "vec", tag = "10")]
    pub checkpoint_block_hash: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "11")]
    pub raw_quote: ::prost::alloc::vec::Vec<u8>,
}
/// Generated server implementations.
pub mod private_compact_tx_streamer_server {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value
    )]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with PrivateCompactTxStreamerServer.
    #[async_trait]
    pub trait PrivateCompactTxStreamer: std::marker::Send + std::marker::Sync + 'static {
        async fn query_page(
            &self,
            request: tonic::Request<super::FixedEnvelope>,
        ) -> std::result::Result<tonic::Response<super::FixedEnvelope>, tonic::Status>;
        async fn bootstrap_session(
            &self,
            request: tonic::Request<super::BootstrapRequest>,
        ) -> std::result::Result<tonic::Response<super::BootstrapResponse>, tonic::Status>;
        async fn get_evidence(
            &self,
            request: tonic::Request<super::EvidenceRequest>,
        ) -> std::result::Result<tonic::Response<super::EvidenceResponse>, tonic::Status>;
    }
    /// Independent private-query surface. This is not the legacy lightwallet API.
    #[derive(Debug)]
    pub struct PrivateCompactTxStreamerServer<T> {
        inner: Arc<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    impl<T> PrivateCompactTxStreamerServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(inner: T, interceptor: F) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>> for PrivateCompactTxStreamerServer<T>
    where
        T: PrivateCompactTxStreamer,
        B: Body + std::marker::Send + 'static,
        B::Error: Into<StdError> + std::marker::Send + 'static,
    {
        type Response = http::Response<tonic::body::Body>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            match req.uri().path() {
                "/zaino.private.v1.PrivateCompactTxStreamer/QueryPage" => {
                    #[allow(non_camel_case_types)]
                    struct QueryPageSvc<T: PrivateCompactTxStreamer>(pub Arc<T>);
                    impl<T: PrivateCompactTxStreamer>
                        tonic::server::UnaryService<super::FixedEnvelope> for QueryPageSvc<T>
                    {
                        type Response = super::FixedEnvelope;
                        type Future = BoxFuture<tonic::Response<Self::Response>, tonic::Status>;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::FixedEnvelope>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as PrivateCompactTxStreamer>::query_page(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = QueryPageSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/zaino.private.v1.PrivateCompactTxStreamer/BootstrapSession" => {
                    #[allow(non_camel_case_types)]
                    struct BootstrapSessionSvc<T: PrivateCompactTxStreamer>(pub Arc<T>);
                    impl<T: PrivateCompactTxStreamer>
                        tonic::server::UnaryService<super::BootstrapRequest>
                        for BootstrapSessionSvc<T>
                    {
                        type Response = super::BootstrapResponse;
                        type Future = BoxFuture<tonic::Response<Self::Response>, tonic::Status>;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::BootstrapRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as PrivateCompactTxStreamer>::bootstrap_session(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = BootstrapSessionSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/zaino.private.v1.PrivateCompactTxStreamer/GetEvidence" => {
                    #[allow(non_camel_case_types)]
                    struct GetEvidenceSvc<T: PrivateCompactTxStreamer>(pub Arc<T>);
                    impl<T: PrivateCompactTxStreamer>
                        tonic::server::UnaryService<super::EvidenceRequest> for GetEvidenceSvc<T>
                    {
                        type Response = super::EvidenceResponse;
                        type Future = BoxFuture<tonic::Response<Self::Response>, tonic::Status>;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::EvidenceRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as PrivateCompactTxStreamer>::get_evidence(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetEvidenceSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => Box::pin(async move {
                    let mut response = http::Response::new(tonic::body::Body::default());
                    let headers = response.headers_mut();
                    headers.insert(
                        tonic::Status::GRPC_STATUS,
                        (tonic::Code::Unimplemented as i32).into(),
                    );
                    headers.insert(
                        http::header::CONTENT_TYPE,
                        tonic::metadata::GRPC_CONTENT_TYPE,
                    );
                    Ok(response)
                }),
            }
        }
    }
    impl<T> Clone for PrivateCompactTxStreamerServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    /// Generated gRPC service name
    pub const SERVICE_NAME: &str = "zaino.private.v1.PrivateCompactTxStreamer";
    impl<T> tonic::server::NamedService for PrivateCompactTxStreamerServer<T> {
        const NAME: &'static str = SERVICE_NAME;
    }
}
